---
- name: Install ELK-stack
  hosts: vm-servers
  remote_user: root
  # become: yes
  # become_method: sudo

  roles:
    - common-software
    - nginx
    - geerlingguy.node
    - ANXS.postgresql
    - geerlingguy.java
    - geerlingguy.filebeat
