---
filebeat_create_config: true

filebeat_prospectors:
  - input_type: log
    paths:
      - "/var/log/*.log"

filebeat_output_elasticsearch_enabled: false

filebeat_output_logstash_enabled: true
filebeat_output_logstash_hosts:
  - "{{ log_server_host }}:5044"

logstash_ssl_dir: /etc/pki/logstash
logstash_ssl_certificate_file: "logstash-forwarder.crt"
filebeat_output_logstash_ca_enabled: true
filebeat_output_logstash_ca: "{{ logstash_ssl_dir }}/{{ logstash_ssl_certificate_file }}"

filebeat_enable_logging: false
filebeat_log_level: warning
filebeat_log_dir: /var/log/mybeat
filebeat_log_filename: mybeat.log
